### ISSUE TITLE
Rotational motion model

### ISSUE THREAD

**Issue by robin-shaun** [remindof/EV-MotionSeg#2]
Hello, I'm reading the paper and I'm curious about the rotational motion model.
![image](https://user-images.githubusercontent.com/20561850/104711917-ed03f780-575c-11eb-977e-147c21c6bfca.png)
The paper says that the fan is represented by a rotational motion model and the coin by a linear velocity motion model, but doesn't give the details. 
The paper _A Unifying Contrast Maximization Framework for Event Cameras, with Applications to Motion, Depth, and Optical Flow Estimation_ gives the rotational model for camera ego-motion. I wonder whether this is the same.
Hope to hear your opinion, thanks a lot~

**Comment by remindof** [comment]
I think the rotation model means how to describe rotation on the 2D image
plane. For example, given a center (*x, y*) and a rotating speed *alpha,*
the event flow can be determined.

The rotation model here is different from the (3-D) rotation model that
describes camera ego-motion.

**Comment by robin-shaun** [comment]
OK, thanks a lot~
